---
title: "Teaching"
output: html_document
---

# {.tabset .tabset-pills .tabset-pills .tabset-pills}


## Development economics {.tabset .tabset-fade .tabset-fade}

### Master

Fall 2020

- [Introduction](https://www.dropbox.com/s/n1f20yshfaiyz0x/Introduction.pdf?dl=0)

- [Review of empirics](https://www.dropbox.com/s/xzx9f75xt6qdi6j/Empirics.pdf?dl=0) 

- [Early theories](https://www.dropbox.com/s/iijaik0zn3h9xjo/Earlytheories.pdf?dl=0)

- [Industrial policy](https://www.dropbox.com/s/4yvnq0ybsyxc1kf/Industrialpolicy.pdf?dl=0)

- [Institutions](https://www.dropbox.com/s/bnwmptwcaiw0829/institutions.pdf?dl=0)

- [Poverty](https://www.dropbox.com/s/nebqrk7fv8sbm9t/poverty.pdf?dl=0) 

- [Mobility](https://www.dropbox.com/s/j793jf13jcdd2re/mobility.pdf?dl=0)

- [Finance and development](https://www.dropbox.com/s/io68ycsb2hyl1yr/Finance.pdf?dl=0)

Slides from previous years:

- Labor market: [part 1](https://www.dropbox.com/s/wy8sk9rds6mflty/DevMSC13.pdf?dl=1) |   [part 2](https://www.dropbox.com/s/9a5ofrtccalgrjy/DevMSC14.pdf?dl=1) |  [part 3](https://www.dropbox.com/s/5kax9dwkxgdtbs8/DevMSC15.pdf?dl=1)

- [Resource curse](https://www.dropbox.com/s/q7s3z4vfgl8a7gn/DevMSC11.pdf?dl=1)


### PhD
- [syllabus](https://www.dropbox.com/s/iurbfjuotqpiofy/Course%20syllabus.docx?dl=1)    
- [slides](https://www.dropbox.com/s/ir6kgh9cm72pxnf/DevPhD.pdf?dl=1)

## Econometrics {.tabset .tabset-fade .tabset-fade}


- [Introduction](https://www.dropbox.com/s/rrh8nzo805dbg5r/Lecture%201-%20introduction.pdf?dl=0)
- [Causality](https://www.dropbox.com/s/oglm5tjuumr6x87/Lecture%202%20-%20Causality.pdf?dl=0)
- [Regression Basics](https://www.dropbox.com/s/l48cwelmnx53yrf/Lecture%203%20-%20Regression.pdf?dl=0)
- [Maximum Likelihood](https://www.dropbox.com/s/y0bu9u0l60ned1a/Lecture%204%20-%20MLL.pdf?dl=0)
- [Generalized Method of Moments](https://www.dropbox.com/s/xsbztrqc9xzhf4r/Lecture%205%20-%20GMM.pdf?dl=0)
- [Discrete Choice Models](https://www.dropbox.com/s/gvur1k5pvj9e1s8/Lecture%206%20-%20Binary%20choice.pdf?dl=0)
- [Panel Data](https://www.dropbox.com/s/qmyepnfoxf6vpa4/Lecture%2010%20-%20Panel%20data.pdf?dl=0)
- [Selection Problem & Randomized Experiments](https://www.dropbox.com/s/52qmuwkcx8s9jwq/Lecture%207%20-%20Selection%20bias%2C%20experiments.pdf?dl=0)
- [Regression and Causality](https://www.dropbox.com/s/zqdg3i9boj0dx8e/Lecture%208%20-%20Regression%20and%20causality.pdf?dl=0)
- [Matching](https://www.dropbox.com/s/krs9tbwoyapj7fb/Lecture%209%20-%20Matching.pdf?dl=0)
- [Instrumental Variable](https://www.dropbox.com/s/7g0p5nt0sg17zsu/Lecture%2010%20-%20IV.pdf?dl=0)
- [Difference-in-difference](https://www.dropbox.com/s/l36ubogrgg8lfb0/Lecture%2011%20-%20DID.pdf?dl=0)
- [Regression Discountinuity Design](https://www.dropbox.com/s/5156e886mw1tbgh/Lecture%2012%20-%20RD.pdf?dl=0)


## Microeconomics {.tabset .tabset-fade .tabset-fade}

### PhD 
- [Preference and choice](https://www.dropbox.com/s/jbd8thpuhzg57ao/MicroPhD1.pdf?dl=1)
- [Consumer choice]() 
- [Classical demand theory]()
- [Aggregate demand]()
- [Production]()
- [Choice under uncertainty]()   

### Master
- [Introduction](https://www.dropbox.com/s/9u93c63x01qmo8z/intro.pdf?dl=1)
- [Consumer theory](https://www.dropbox.com/s/pxqtqo9rk9k8ojc/CONSUMER.pdf?dl=1) 
- [Uncertainty](https://www.dropbox.com/s/itzp0ic92oye8m4/risk.pdf?dl=1)
- [Theory of the Firm](https://www.dropbox.com/s/76zv8340vf0wpkp/firm.pdf?dl=1)
- [Partial equilibrium](https://www.dropbox.com/s/vxkp12oo535ai1l/partial%20equilibrium.pdf?dl=1)


[//]: <> (## Public economics)
[//]: <> (- [syllabus](https://www.dropbox.com/s/srfpjiz1t5l19kx/Taxation%20syllabus.docx?dl=1))    



## Softwares {.tabset .tabset-fade .tabset-fade}

### STATA
- [Introduction](rstata.html)

[//]: <> (- [Exercise 1](https://www.dropbox.com/s/hem67p300cfgetj/Stata1.pdf?dl=1)
- [Exercise 2](https://www.dropbox.com/s/528kdc375f2fepq/Stata2.pdf?dl=1)
- [Exercise 3](https://www.dropbox.com/s/9hjyd2hv3n6t9to/Stata3.pdf?dl=1))

### R
- [Introduction](https://www.dropbox.com/s/57zbl4d72w60yae/01-Intro.pdf?dl=1)
- [Basics](https://www.dropbox.com/s/mfmo0zclcsgy95q/02-The-R-Language-Part-1.pdf?dl=1)
- [R language](https://www.dropbox.com/s/mal5m1p61uuut1w/03-The-R-Language-Part-2.pdf?dl=1)
- [Visualization](https://www.dropbox.com/s/6iqja01owwhpfee/04-Visualizing-Data.pdf?dl=1)
- [Adjusting graphs](https://www.dropbox.com/s/8rmabq79n1yojeb/05-Adjusting-Graphs.pdf?dl=1)
- [Tidy data](https://www.dropbox.com/s/sex16ruyvw1m5uo/06-Tidy-Data.pdf?dl=1)
- [Transforming data](https://www.dropbox.com/s/q4d3p7uoc80y5hk/07-Transforming-Data.pdf?dl=0)
